# Ridge Regression with GD

In [1]:
import numpy as np
import pandas as pd

from sklearn.datasets import load_diabetes
from sklearn.model_selection import train_test_split
from sklearn.linear_model import SGDRegressor,Ridge

from sklearn.metrics import r2_score

In [2]:
x,y=load_diabetes(return_X_y=True)

In [3]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=4)

In [6]:
sgd=SGDRegressor(max_iter=500,eta0=0.001,penalty='l2',learning_rate='constant')

sgd.fit(x_train,y_train)
y_pred=sgd.predict(x_test)
sgd.intercept_,sgd.coef_,r2_score(y_pred,y_test)

c:\Users\moury\AppData\Local\Programs\Python\Python313\Lib\site-packages\sklearn\linear_model\_stochastic_gradient.py:1608: ConvergenceWarning: Maximum number of iteration reached before convergence. Consider increasing max_iter to improve the fit.
  warnings.warn(


(array([151.64497977]),
 array([  59.34162671,  -37.35767997,  234.04496465,  180.91614826,
          43.75136562,   15.36551639, -135.56249774,  134.4163852 ,
         221.72359772,  112.54120598]),
 -1.678739649379307)

In [8]:
rr=Ridge(alpha=0.001,max_iter=500,solver='sparse_cg')

rr.fit(x_train,y_train)
y_pred=rr.predict(x_test)
rr.intercept_,rr.coef_,r2_score(y_pred,y_test)

(np.float64(151.10198517439466),
 array([  34.52192544, -290.84084076,  482.40181344,  368.0678662 ,
        -852.44873179,  501.59160336,  180.11115788,  270.76333979,
         759.73534372,   37.4913546 ]),
 -0.10861356490818341)

In [16]:
class RGD:
    def __init__(self,alpha=0.1,epochs=100,learning_rate=0.1):
        self.epochs=epochs
        self.n=learning_rate
        self.alpha=alpha
        self.coef_=None
        self.intercept_=None

    def fit(self,x_train,y_train):
        
        self.coef_=np.ones(x_train.shape[1])
        self.intercept_=0
        thetha=np.insert(self.coef_,0,self.intercept_)
        x_train=np.insert(x_train,0,1,axis=1)

        for i in range(self.epochs):
            thetha_dr=np.dot(x_train.T,x_train).dot(thetha)-np.dot(x_train.T,y_train)-self.alpha*thetha
            thetha=thetha-self.n*thetha_dr
        self.coef_=thetha[1:]
        self.intercept_=thetha[0]

    def predict(self,x_test):
        y_pred=self.intercept_+(np.dot(x_test,self.coef_))
        return y_pred

In [24]:
rr=RGD(alpha=0.001,epochs=500,learning_rate=0.005)

rr.fit(x_train,y_train)
y_pred=rr.predict(x_test)
rr.intercept_,rr.coef_,r2_score(y_pred,y_test)

(np.float64(150.86907936929475),
 array([  46.62140947, -221.88627741,  452.72916665,  325.94986339,
         -29.28550185,  -96.76767049, -191.05382527,  146.37675246,
         401.31596569,   95.03232584]),
 -0.22367209834589552)